export const DataVacunas = [
    {
        id: 1,
        nombre: "BCG",
        intro: "La vacuna BCG (Bacilo de Calmette-Guérin) es una vacuna utilizada para prevenir la tuberculosis (TB). Recibe su nombre en honor a los científicos franceses Albert Calmette y Camille Guérin, quienes desarrollaron la vacuna a principios del siglo XX. La BCG es una vacuna viva atenuada que contiene una forma debilitada de la bacteria Mycobacterium bovis, que es similar a la bacteria que causa la tuberculosis en los seres humanos.",
        dosis: "La vacuna BCG se administra en una sola dosis a los niños de manera intradérmica (bajo la piel). Normalmente se administra poco después del nacimiento, preferiblemente antes de que el bebé cumpla un mes de edad.",
        eficacia: "La eficacia de la vacuna BCG varía según la geografía y la cepa utilizada en la vacuna. En general, la vacuna BCG proporciona una protección moderada contra las formas graves de tuberculosis en niños pequeños. Es especialmente efectiva en la prevención de la tuberculosis miliar y la meningitis tuberculosa en niños.",
        efectos: "En general, la vacuna BCG es segura, pero puede causar algunos efectos secundarios. Después de la vacunación, es común que se forme una pequeña lesión en el lugar de la inyección, que puede desarrollar una úlcera y luego formar una cicatriz. Algunos niños también pueden experimentar inflamación de los ganglios linfáticos cercanos al lugar de la inyección. En casos muy raros, pueden ocurrir complicaciones graves, como infecciones diseminadas. Estas complicaciones son extremadamente poco frecuentes y suelen ocurrir en niños con sistemas inmunológicos debilitados.",
        simultaneo:"La vacuna BCG se puede administrar de forma simultánea con otras vacunas, como las vacunas contra la difteria, el tétanos, la pertussis, la poliomielitis y la hepatitis B. Sin embargo, es importante consultar con un profesional de la salud para determinar la mejor programación de las vacunas y asegurarse de que cumplan con las pautas y recomendaciones locales.",
        historia: "La vacuna BCG fue desarrollada por Albert Calmette y Camille Guérin en Francia a principios del siglo XX. Los científicos trabajaron en la atenuación de la bacteria Mycobacterium bovis para utilizarla como una vacuna contra la tuberculosis. Después de varias décadas de investigación y pruebas, la vacuna BCG se introdujo en el uso clínico en la década de 1920."
    }, 
    
    {
        id: 2,
        nombre: "HB pediátrica cero",
        intro: "La vacuna HB pediátrica cero es una vacuna utilizada para prevenir la hepatitis B en los niños. La hepatitis B es una infección viral que afecta al hígado y puede causar enfermedades graves. La vacuna HB pediátrica cero contiene antígenos del virus de la hepatitis B y ayuda a estimular la respuesta inmunológica del cuerpo para combatir la infección viral.",
        dosis: "La vacuna HB pediátrica cero se administra en varias dosis, según el calendario de vacunación recomendado por las autoridades sanitarias. Generalmente, se administra una primera dosis poco después del nacimiento, preferiblemente dentro de las primeras 24 horas de vida. Posteriormente, se administran dosis adicionales en los meses siguientes, siguiendo un programa de vacunación específico.",
        eficacia: "La vacuna HB pediátrica cero es altamente efectiva para prevenir la infección por el virus de la hepatitis B en los niños. Proporciona una respuesta inmunológica adecuada en la mayoría de los casos, lo que ayuda a proteger al organismo contra la enfermedad. Sin embargo, es importante seguir el programa completo de dosis para asegurar una protección adecuada.",
        efectos: "En general, la vacuna HB pediátrica cero es segura y bien tolerada. Los efectos secundarios más comunes son leves y transitorios, como dolor o enrojecimiento en el lugar de la inyección. En raras ocasiones, se pueden presentar reacciones alérgicas, pero son extremadamente poco frecuentes. Siempre es importante notificar al profesional de la salud cualquier reacción adversa después de la vacunación.",
        simultaneo: "La vacuna HB pediátrica cero se puede administrar de forma simultánea con otras vacunas pediátricas recomendadas, como las vacunas contra difteria, tétanos, pertussis, poliomielitis, entre otras. La administración simultánea de varias vacunas permite optimizar el programa de inmunización y reducir la necesidad de visitas médicas adicionales.",
        historia: "La vacuna HB pediátrica cero fue desarrollada para prevenir la infección por el virus de la hepatitis B en los niños. A medida que se comprendió mejor la transmisión de la hepatitis B de madre a hijo durante el parto, se implementó la estrategia de administrar la primera dosis de la vacuna poco después del nacimiento para proporcionar una protección temprana. La vacuna ha demostrado ser eficaz en la prevención de la infección por el virus de la hepatitis B y ha sido ampliamente utilizada en programas de vacunación infantil en todo el mundo."
    },

    {
        id: 3,
        nombre: "Rotavirus",
        intro: "La vacuna Rotavirus es una vacuna utilizada para prevenir la infección por el virus del rotavirus, que es una de las principales causas de diarrea grave en los niños. El rotavirus puede causar deshidratación severa y complicaciones en los bebés y niños pequeños. La vacuna contiene partículas del virus del rotavirus que han sido debilitadas o inactivadas para estimular una respuesta inmunológica protectora en el organismo.",
        dosis: "La vacuna Rotavirus se administra en varias dosis, generalmente por vía oral. La cantidad y el intervalo de dosis varían según el tipo de vacuna utilizado. Las primeras dosis suelen administrarse a partir de las 6 semanas de vida, y se completan antes de los 8 meses de edad, siguiendo el programa de vacunación recomendado.",
        eficacia: "La vacuna Rotavirus es altamente efectiva para prevenir la enfermedad grave causada por el virus del rotavirus. Proporciona una protección significativa contra la diarrea por rotavirus, reduciendo la gravedad de los síntomas y disminuyendo el riesgo de hospitalización. Sin embargo, es importante tener en cuenta que la vacuna no previene todas las infecciones por rotavirus, pero ayuda a reducir su impacto.",
        efectos: "En general, la vacuna Rotavirus es segura y bien tolerada. Los efectos secundarios más comunes son leves e incluyen irritabilidad, fiebre baja o moderada y diarrea leve. Estos efectos suelen ser temporales y desaparecen por sí solos. En casos muy raros, pueden ocurrir complicaciones graves, pero son extremadamente infrecuentes.",
        simultaneo: "La vacuna Rotavirus se puede administrar de forma simultánea con otras vacunas recomendadas en el programa de inmunización infantil, como las vacunas contra difteria, tétanos, pertussis, poliomielitis, entre otras. La administración simultánea de varias vacunas ayuda a optimizar la protección del niño y simplificar el proceso de vacunación.",
        historia: "La vacuna Rotavirus fue desarrollada para abordar la carga significativa de enfermedades diarreicas causadas por el rotavirus en los niños. Después de años de investigación y desarrollo, las primeras vacunas contra el rotavirus fueron autorizadas para su uso en la década de 2000. Desde entonces, la vacuna ha sido incluida en los programas de inmunización infantil en muchos países, lo que ha contribuido a reducir la morbilidad y la mortalidad relacionadas con la infección por rotavirus."        
    },

    {
        id: 4,
        nombre: "fIPV (Vacuna Inactivada de Polio)",
        intro: "La vacuna fIPV, también conocida como Vacuna Inactivada de Polio, es una vacuna utilizada para prevenir la poliomielitis, una enfermedad viral altamente contagiosa que afecta principalmente al sistema nervioso. La fIPV contiene virus de la polio inactivados, lo que significa que no pueden causar la enfermedad, pero estimulan una respuesta inmunológica en el organismo para protegerlo contra la polio.",
        dosis: "La vacuna fIPV se administra en varias dosis, generalmente por vía intramuscular. El número y el intervalo de las dosis pueden variar según las pautas y recomendaciones de cada país. Normalmente, se administran varias dosis durante la infancia, seguidas de dosis de refuerzo en la edad adulta.",
        eficacia: "La vacuna fIPV es altamente efectiva para prevenir la poliomielitis. Estimula una respuesta inmunológica que ayuda a proteger al organismo contra los tipos de poliovirus incluidos en la vacuna. La inmunización con la fIPV ha sido clave en los esfuerzos para eliminar la polio en muchas partes del mundo.",
        efectos: "En general, la vacuna fIPV es segura y bien tolerada. Los efectos secundarios son generalmente leves y transitorios, como enrojecimiento o dolor en el lugar de la inyección. En raras ocasiones, pueden ocurrir reacciones alérgicas, pero son extremadamente poco frecuentes.",
        simultaneo: "La vacuna fIPV se puede administrar de forma simultánea con otras vacunas recomendadas, como las vacunas contra difteria, tétanos, pertussis, hepatitis B, entre otras. La administración simultánea de varias vacunas permite optimizar el programa de vacunación y reducir la necesidad de visitas médicas adicionales.",
        historia: "La vacuna fIPV fue desarrollada como parte de los esfuerzos globales para erradicar la polio. Se han utilizado diferentes tipos de vacunas a lo largo del tiempo, y la fIPV, que contiene virus de la polio inactivados, ha demostrado ser segura y efectiva en la prevención de la enfermedad. Gracias a las campañas de vacunación masiva, la polio ha sido eliminada en la mayoría de los países, y la fIPV sigue siendo una herramienta fundamental en la lucha contra esta enfermedad."
    },


    {
        id: 5,
        nombre: "bOPV (Vacuna Oral de Polio Bivalente)",
        intro: "La vacuna bOPV, también conocida como Vacuna Oral de Polio Bivalente, es una vacuna utilizada para prevenir la poliomielitis, una enfermedad viral altamente contagiosa que afecta principalmente al sistema nervioso. La bOPV contiene virus de la polio atenuados, lo que significa que están debilitados y no pueden causar la enfermedad, pero estimulan una respuesta inmunológica en el organismo para protegerlo contra la polio.",
        dosis: "La vacuna bOPV se administra en varias dosis, generalmente por vía oral. El número y el intervalo de las dosis pueden variar según las pautas y recomendaciones de cada país. Normalmente, se administran varias dosis durante la infancia, seguidas de dosis de refuerzo en la edad adulta.",
        eficacia: "La vacuna bOPV es altamente efectiva para prevenir la poliomielitis. Estimula una respuesta inmunológica que ayuda a proteger al organismo contra los tipos de poliovirus incluidos en la vacuna. La inmunización con bOPV ha sido clave en los esfuerzos para eliminar la polio en muchas partes del mundo.",
        efectos: "En general, la vacuna bOPV es segura y bien tolerada. Los efectos secundarios son generalmente leves y transitorios, como diarrea o molestias abdominales. Estos efectos suelen ser temporales y desaparecen por sí solos. En raras ocasiones, pueden ocurrir complicaciones graves, pero son extremadamente poco frecuentes.",
        simultaneo: "La vacuna bOPV se puede administrar de forma simultánea con otras vacunas recomendadas, como las vacunas contra difteria, tétanos, pertussis, hepatitis B, entre otras. La administración simultánea de varias vacunas permite optimizar el programa de vacunación y reducir la necesidad de visitas médicas adicionales.",
        historia: "La vacuna bOPV fue desarrollada como parte de los esfuerzos globales para erradicar la polio. Se ha utilizado ampliamente en programas de inmunización en todo el mundo y ha sido fundamental para reducir la incidencia de la enfermedad. Gracias a las campañas masivas de vacunación, la polio ha sido eliminada en la mayoría de los países, y la bOPV sigue siendo una herramienta esencial para prevenir la propagación del virus."  
    },

    {
        id: 6,
        nombre: "Pentavalente (DPT+HB+Hib)",
        intro: "La vacuna Pentavalente, también conocida como DPT+HB+Hib, es una vacuna combinada utilizada para prevenir múltiples enfermedades en niños. Contiene componentes para la protección contra la difteria, tos ferina (pertussis), tétanos, hepatitis B y Haemophilus influenzae tipo b (Hib). La vacuna combina diferentes antígenos para estimular una respuesta inmunológica efectiva contra estas enfermedades.",
        dosis: "La vacuna Pentavalente se administra en varias dosis, generalmente por vía intramuscular. El número y el intervalo de las dosis pueden variar según las pautas y recomendaciones de cada país. Normalmente, se administran varias dosis durante la infancia, con dosis de refuerzo en etapas posteriores de la vida.",
        eficacia: "La vacuna Pentavalente es altamente eficaz en la prevención de las enfermedades incluidas en su composición. Proporciona protección contra la difteria, tos ferina, tétanos, hepatitis B y Haemophilus influenzae tipo b. La inmunización con Pentavalente ha demostrado ser efectiva en la reducción de la incidencia y gravedad de estas enfermedades.",
        efectos: "En general, la vacuna Pentavalente es segura y bien tolerada. Los efectos secundarios son generalmente leves y transitorios, como enrojecimiento o dolor en el lugar de la inyección, fiebre o irritabilidad. Estos efectos suelen ser temporales y desaparecen por sí solos. En raras ocasiones, pueden ocurrir reacciones alérgicas, pero son extremadamente poco frecuentes.",
        simultaneo: "La vacuna Pentavalente se puede administrar de forma simultánea con otras vacunas recomendadas, como las vacunas contra polio, rotavirus, neumococo y otras enfermedades. La administración simultánea de varias vacunas permite optimizar el programa de vacunación y reducir la necesidad de visitas médicas adicionales.",
        historia: "La vacuna Pentavalente fue desarrollada para proporcionar una protección más amplia y completa contra múltiples enfermedades en un solo producto. La combinación de diferentes antígenos en una sola vacuna ha simplificado el proceso de vacunación y ha sido fundamental en los esfuerzos para controlar y reducir la incidencia de estas enfermedades en la población infantil."
    },

    {
        id: 7,
        nombre: "Influenza Pediátrica",
        intro: "La vacuna Influenza Pediátrica es una vacuna utilizada para prevenir la influenza en niños. La influenza, comúnmente conocida como gripe, es una enfermedad respiratoria contagiosa causada por los virus de la influenza. La vacuna está diseñada para estimular una respuesta inmunológica en el organismo, proporcionando protección contra las cepas virales de la influenza que circulan durante la temporada.",
        dosis: "La vacuna Influenza Pediátrica se administra en una o dos dosis, dependiendo de la edad del niño y las pautas específicas de vacunación de cada país. La vacuna se administra por vía intramuscular y se recomienda recibir una dosis anualmente, antes del comienzo de la temporada de influenza.",
        eficacia: "La vacuna Influenza Pediátrica tiene una eficacia variable en la prevención de la influenza, ya que la efectividad puede verse afectada por la coincidencia entre las cepas virales incluidas en la vacuna y las cepas circulantes en cada temporada. Sin embargo, se ha demostrado que la vacuna reduce la gravedad de la enfermedad en aquellos que aún se infectan y puede prevenir complicaciones graves.",
        efectos: "En general, la vacuna Influenza Pediátrica es segura y bien tolerada. Los efectos secundarios son generalmente leves y transitorios, como enrojecimiento o dolor en el lugar de la inyección, fiebre baja o malestar general. En raras ocasiones, pueden ocurrir reacciones alérgicas, pero son extremadamente poco frecuentes.",
        simultaneo: "La vacuna Influenza Pediátrica se puede administrar de forma simultánea con otras vacunas recomendadas, como las vacunas contra difteria, tétanos, pertussis, hepatitis B, entre otras. La administración simultánea de varias vacunas permite optimizar el programa de vacunación y reducir la necesidad de visitas médicas adicionales.",
        historia: "La vacuna Influenza Pediátrica ha sido desarrollada y actualizada continuamente para adaptarse a las cepas virales que circulan durante cada temporada de influenza. Es parte de los esfuerzos de salud pública para prevenir la propagación de la enfermedad y reducir su impacto en la población infantil. La vacunación anual contra la influenza es recomendada para proteger a los niños y prevenir la propagación del virus."


    },

    {
        id: 8,
        nombre: "DPT (Difteria, Tétanos y Tosferina)",
        intro: "La vacuna DPT es una vacuna combinada que protege contra tres enfermedades: difteria, tétanos y tosferina (pertussis). Estas enfermedades son causadas por bacterias y pueden ser graves e incluso mortales, especialmente en niños pequeños. La vacuna DPT contiene toxoides y antígenos inactivados que estimulan una respuesta inmunológica para proteger al organismo contra estas enfermedades.",
        dosis: "La vacuna DPT se administra en varias dosis, generalmente por vía intramuscular. El número y el intervalo de las dosis pueden variar según las pautas y recomendaciones de cada país. Normalmente, se administran varias dosis durante la infancia, con dosis de refuerzo en etapas posteriores de la vida para mantener la protección.",
        eficacia: "La vacuna DPT es altamente eficaz en la prevención de la difteria, el tétanos y la tosferina. Estimula una respuesta inmunológica que ayuda a proteger al organismo contra estas enfermedades. La inmunización con DPT ha demostrado ser efectiva en la reducción de la incidencia y gravedad de estas enfermedades.",
        efectos: "En general, la vacuna DPT es segura y bien tolerada. Los efectos secundarios son generalmente leves y transitorios, como enrojecimiento o dolor en el lugar de la inyección, fiebre baja o malestar general. En raras ocasiones, pueden ocurrir reacciones alérgicas, pero son extremadamente poco frecuentes.",
        simultaneo: "La vacuna DPT se puede administrar de forma simultánea con otras vacunas recomendadas, como las vacunas contra polio, hepatitis B, Hib y otras enfermedades. La administración simultánea de varias vacunas permite optimizar el programa de vacunación y reducir la necesidad de visitas médicas adicionales.",
        historia: "La vacuna DPT ha sido ampliamente utilizada en programas de inmunización en todo el mundo y ha sido fundamental en la reducción de la incidencia de la difteria, el tétanos y la tosferina. La combinación de estas tres vacunas en una sola inyección ha simplificado el proceso de vacunación y ha sido clave en la protección de la población, especialmente los niños, contra estas enfermedades."
    },

    {
        id: 9,
        nombre: "SRP (Sarampión, Rubéola y Parotiditis)",
        intro: "La vacuna SRP es una vacuna combinada utilizada para prevenir tres enfermedades altamente contagiosas: sarampión, rubéola y parotiditis (paperas). Estas enfermedades son causadas por virus y pueden tener complicaciones graves. La vacuna SRP contiene virus vivos atenuados que estimulan una respuesta inmunológica para proteger al organismo contra estas enfermedades.",
        dosis: "La vacuna SRP se administra en dos dosis, generalmente por vía subcutánea. La primera dosis se administra en la infancia, generalmente entre los 12 y 15 meses de edad, y la segunda dosis se administra en la etapa preescolar, generalmente entre los 4 y 6 años de edad. Estas dosis proporcionan una protección duradera contra el sarampión, la rubéola y las paperas.",
        eficacia: "La vacuna SRP es altamente eficaz en la prevención del sarampión, la rubéola y las paperas. Estimula una respuesta inmunológica que ayuda a proteger al organismo contra estas enfermedades. La inmunización con SRP ha demostrado ser efectiva en la reducción de la incidencia y gravedad de estas enfermedades, así como en la prevención de complicaciones y brotes.",
        efectos: "En general, la vacuna SRP es segura y bien tolerada. Los efectos secundarios son generalmente leves y transitorios, como enrojecimiento o dolor en el lugar de la inyección, fiebre baja o erupción cutánea leve. En raras ocasiones, pueden ocurrir reacciones alérgicas, pero son extremadamente poco frecuentes.",
        simultaneo: "La vacuna SRP se puede administrar de forma simultánea con otras vacunas recomendadas, como las vacunas contra difteria, tétanos, pertussis, hepatitis B y otras enfermedades. La administración simultánea de varias vacunas permite optimizar el programa de vacunación y reducir la necesidad de visitas médicas adicionales.",
        historia: "La vacuna SRP ha sido ampliamente utilizada en programas de inmunización a nivel mundial y ha sido crucial en la reducción de la incidencia del sarampión, la rubéola y las paperas. La combinación de estas tres vacunas en una sola inyección ha simplificado el proceso de vacunación y ha contribuido a la protección de la población, especialmente los niños, contra estas enfermedades altamente contagiosas."
    },

    {
        id: 10,
        nombre: "FA (Fiebre Amarilla)",
        intro: "La vacuna FA es una vacuna utilizada para prevenir la fiebre amarilla, una enfermedad viral transmitida por mosquitos. La fiebre amarilla puede causar síntomas graves, incluyendo fiebre alta, ictericia, hemorragias y, en algunos casos, puede ser mortal. La vacuna FA contiene una forma debilitada del virus que estimula una respuesta inmunológica para proteger al organismo contra la enfermedad.",
        dosis: "La vacuna FA se administra en una sola dosis, generalmente por vía subcutánea. Esta dosis proporciona una protección duradera contra la fiebre amarilla. Es importante recibir la vacuna al menos 10 días antes de viajar a áreas donde la fiebre amarilla es endémica, ya que se requiere tiempo para que el organismo desarrolle una respuesta inmunológica adecuada.",
        eficacia: "La vacuna FA es altamente eficaz en la prevención de la fiebre amarilla. Estimula una respuesta inmunológica que ayuda a proteger al organismo contra la enfermedad. Se ha demostrado que la vacuna proporciona inmunidad a largo plazo en la mayoría de las personas vacunadas.",
        efectos: "En general, la vacuna FA es segura y bien tolerada. Los efectos secundarios son generalmente leves y transitorios, como enrojecimiento o dolor en el lugar de la inyección, fiebre baja o malestar general. En raras ocasiones, pueden ocurrir reacciones alérgicas, pero son extremadamente poco frecuentes.",
        simultaneo: "La vacuna FA se puede administrar de forma simultánea con otras vacunas recomendadas. Sin embargo, es importante consultar las pautas específicas de vacunación y las recomendaciones de los expertos en salud para determinar el mejor momento y esquema de vacunación.",
        historia: "La vacuna FA ha sido utilizada durante décadas como parte de los esfuerzos de salud pública para prevenir la propagación de la fiebre amarilla. La vacunación masiva ha sido clave en la reducción de la incidencia de la enfermedad en áreas endémicas y en la protección de los viajeros que se desplazan a zonas de riesgo. La vacuna FA es un componente fundamental en la estrategia global de control de la fiebre amarilla."

    },

    {
        id: 11,
        nombre: "Varicela",
        intro: "La vacuna de la Varicela es una vacuna utilizada para prevenir la infección por el virus de la varicela-zóster, que causa la enfermedad de la varicela. La varicela es una infección viral altamente contagiosa que se caracteriza por erupciones cutáneas y fiebre. La vacuna contiene virus vivos atenuados que estimulan una respuesta inmunológica para proteger al organismo contra la enfermedad.",
        dosis: "La vacuna de la Varicela se administra en dos dosis, generalmente por vía subcutánea. La primera dosis se administra en la infancia, generalmente entre los 12 y 15 meses de edad, y la segunda dosis se administra en la etapa preescolar, generalmente entre los 4 y 6 años de edad. Estas dos dosis proporcionan una protección duradera contra la varicela y ayudan a prevenir complicaciones.",
        eficacia: "La vacuna de la Varicela es altamente eficaz en la prevención de la varicela. Estimula una respuesta inmunológica que ayuda a proteger al organismo contra la enfermedad. Se ha demostrado que la vacuna reduce la gravedad de la infección en aquellos que aún la contraen después de la vacunación, lo que resulta en menos complicaciones y una recuperación más rápida.",
        efectos: "En general, la vacuna de la Varicela es segura y bien tolerada. Los efectos secundarios son generalmente leves y transitorios, como enrojecimiento o dolor en el lugar de la inyección, fiebre baja o malestar general. En raras ocasiones, pueden ocurrir reacciones alérgicas, pero son extremadamente poco frecuentes.",
        simultaneo: "La vacuna de la Varicela se puede administrar de forma simultánea con otras vacunas recomendadas, como la vacuna MMR (sarampión, rubéola y parotiditis) y la vacuna contra el tétanos, la difteria y la tos ferina. La administración simultánea de varias vacunas permite optimizar el programa de vacunación y reducir la necesidad de visitas médicas adicionales.",
        historia: "La vacuna de la Varicela ha sido ampliamente utilizada en programas de inmunización para prevenir la propagación de la enfermedad y reducir la incidencia de la varicela. La incorporación de esta vacuna en los programas de vacunación ha demostrado ser efectiva en la disminución de los casos de varicela y sus complicaciones, así como en la protección de la población en general, especialmente los niños."
    },
];